apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeapidepl
  labels:
    app: weather-forecast
spec:
  replicas: 1
  selector:
    matchLabels:
      service: kubeapidepl
  template:
    metadata:
      labels:
        app: weather-forecast
        service: kubeapidepl
    spec:
      containers:
        - name: kubeapidepl
          image: keenoncoding/kubeapidepl:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: kubeapidepl
  labels:
    app: weather-forecast
    service: kubeapidepl
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: kubeapidepl