apiVersion : apps/v1
kind: Deployment
metadata:
  name: kubedeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubedeploy
  template:
    metadata:
      labels:
        app: kubedeploy
    spec:
      containers:
        - name: kubedeploy 
          image: kubedeploycr.azurecr.io/kubedeploy
          imagePullPolicy: Always
          ports:
          - containerPort: 80