apiVersion : apps/v1
kind: Deployment
metadata:
  name: deplclient 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deplclient
  template:
    metadata:
      labels:
        app: deplclient 
    spec:
      containers:
        - name: deplclient 
          image: keenoncoding/deplclient
          imagePullPolicy: Always
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: deplclient-loadbalancer
spec:
    type: LoadBalancer
    selector:
      app: deplclient
    ports:
    - name: deplclient
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: deplclient-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: deplclient
  ports:
    - name: deplclient
      protocol: TCP
      port: 80
      targetPort: 80
